--OBTENER_TABLA_CURSO
CREATE PROCEDURE SP_OBTENER_TABLA_CURSO
AS
BEGIN
SELECT idCurso,curso  FROM Curso
END
GO
EXECUTE SP_OBTENER_TABLA_CURSO 
GO
--INSERTAR_CURSO--
CREATE PROCEDURE SP_INSERTA_CURSO(
@curso VARCHAR(50)
)
AS
BEGIN
INSERT INTO Curso VALUES (@curso)
END
GO
EXECUTE SP_INSERTA_CURSO "MATEMATICA"
GO
--MODIFICAR CURSO--
CREATE PROCEDURE SP_MODIFICAR_CURSO
@idCurso INTEGER,
@curso VARCHAR(50)
AS
BEGIN
UPDATE Curso SET curso=@curso
WHERE idCurso=@idCurso
END
GO
EXECUTE SP_MODIFICAR_CURSO 1,"COMUNICACIÓN" 
GO

--ELIMINAR--
CREATE PROCEDURE SP_ELIMINAR_CURSO
@idCurso INTEGER
AS
BEGIN
DELETE Curso WHERE idCurso=@idCurso
END
GO
EXECUTE SP_ELIMINAR_CURSO 1
GO

--BUSCAR CURSO--
CREATE PROCEDURE SP_BUSCAR_CURSO
@idCurso INTEGER
AS
BEGIN
SELECT* FROM Curso WHERE idCurso=@idCurso
END
GO
EXECUTE SP_BUSCAR_CURSO 2
GO