--OBTENER_TABLA_NOTAS
CREATE PROCEDURE SP_OBTENER_TABLA_NOTA
AS
BEGIN
SELECT N.idNota AS 'IDNOTA' ,A.apellidos AS 'APELLIDO',A.nombre AS 'NOMBRE',C.curso AS 'CURSO',N.nota1 AS 'NOTA_1',N.nota2 AS 'NOTA_2',N.nota3 AS 'NOTA_3',N.nota4 AS 'NOTA_4'
FROM Notas N INNER JOIN Alumnos A ON N.notaAlumno=A.idAlumnos
			 INNER JOIN Curso C ON N.notaCurso=C.idCurso
			 ORDER BY A.apellidos
END
GO
EXECUTE SP_OBTENER_TABLA_NOTA
GO
--OBTENER_TABLA_NOTAS
CREATE PROCEDURE SP_OBTENER_TABLA_NOTAS
AS
BEGIN
SELECT*FROM Notas
END
GO
EXECUTE SP_OBTENER_TABLA_NOTAS
GO
--INSERTAR_CURSO--
CREATE PROCEDURE SP_INSERTA_NOTAS(
	@notaAlumno INTEGER,
	@notaCurso INTEGER,
	@nota1 FLOAT,
	@nota2 FLOAT,
	@nota3 FLOAT,
	@nota4 FLOAT
)
AS
BEGIN
INSERT INTO Notas VALUES (@notaAlumno,@notaCurso,@nota1,@nota2,@nota3,@nota4)
END
GO
EXECUTE SP_INSERTA_NOTAS 1,2,13.2,12,12,12
GO
--MODIFICAR CURSO--
CREATE PROCEDURE SP_MODIFICAR_NOTA
	@idNota INTEGER,
	@notaAlumno INTEGER,
	@notaCurso INTEGER,
	@nota1 FLOAT,
	@nota2 FLOAT,
	@nota3 FLOAT,
	@nota4 FLOAT
AS
BEGIN
UPDATE Notas SET notaAlumno=@notaAlumno,notaCurso=@notaCurso,nota1=@nota1,nota2=@nota2,nota3=@nota3,nota4=@nota4
WHERE idNota=@idNota
END
GO
EXECUTE SP_MODIFICAR_NOTA 1,1,2,12,12,12,12
GO

--ELIMINAR--
CREATE PROCEDURE SP_ELIMINAR_Nota
@idNota INTEGER
AS
BEGIN
DELETE Notas WHERE idNota=@idNota
END
GO
EXECUTE SP_ELIMINAR_Nota 2
GO

--BUSCAR CURSO--
CREATE PROCEDURE SP_BUSCAR_Nota
@idNota INTEGER
AS
BEGIN
SELECT* FROM Notas WHERE idNota=@idNota
END
GO
EXECUTE SP_BUSCAR_Nota 1
GO